version: '3.8'

services:
  backend:
    build:
      context: ./promanage-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=tu-clave-secreta-super-segura
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./promanage-backend:/app
    networks:
      - promanage-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./promanage-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - promanage-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=promanage
      - POSTGRES_USER=promanage_user
      - POSTGRES_PASSWORD=promanage_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - promanage-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - promanage-network
    command: redis-server --appendonly yes

networks:
  promanage-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: